# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lepley/Desktop/Apps/c++/Survive

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lepley/Desktop/Apps/c++/Survive

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lepley/Desktop/Apps/c++/Survive/CMakeFiles /home/lepley/Desktop/Apps/c++/Survive/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lepley/Desktop/Apps/c++/Survive/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named survive

# Build rule for target.
survive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 survive
.PHONY : survive

# fast build rule for target.
survive/fast:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/build
.PHONY : survive/fast

src/bullet.o: src/bullet.cpp.o

.PHONY : src/bullet.o

# target to build an object file
src/bullet.cpp.o:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/bullet.cpp.o
.PHONY : src/bullet.cpp.o

src/bullet.i: src/bullet.cpp.i

.PHONY : src/bullet.i

# target to preprocess a source file
src/bullet.cpp.i:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/bullet.cpp.i
.PHONY : src/bullet.cpp.i

src/bullet.s: src/bullet.cpp.s

.PHONY : src/bullet.s

# target to generate assembly for a file
src/bullet.cpp.s:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/bullet.cpp.s
.PHONY : src/bullet.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/graphics.o: src/graphics.cpp.o

.PHONY : src/graphics.o

# target to build an object file
src/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/graphics.cpp.o
.PHONY : src/graphics.cpp.o

src/graphics.i: src/graphics.cpp.i

.PHONY : src/graphics.i

# target to preprocess a source file
src/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/graphics.cpp.i
.PHONY : src/graphics.cpp.i

src/graphics.s: src/graphics.cpp.s

.PHONY : src/graphics.s

# target to generate assembly for a file
src/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/graphics.cpp.s
.PHONY : src/graphics.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/survive.o: src/survive.cpp.o

.PHONY : src/survive.o

# target to build an object file
src/survive.cpp.o:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/survive.cpp.o
.PHONY : src/survive.cpp.o

src/survive.i: src/survive.cpp.i

.PHONY : src/survive.i

# target to preprocess a source file
src/survive.cpp.i:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/survive.cpp.i
.PHONY : src/survive.cpp.i

src/survive.s: src/survive.cpp.s

.PHONY : src/survive.s

# target to generate assembly for a file
src/survive.cpp.s:
	$(MAKE) -f CMakeFiles/survive.dir/build.make CMakeFiles/survive.dir/src/survive.cpp.s
.PHONY : src/survive.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... survive"
	@echo "... src/bullet.o"
	@echo "... src/bullet.i"
	@echo "... src/bullet.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/graphics.o"
	@echo "... src/graphics.i"
	@echo "... src/graphics.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/survive.o"
	@echo "... src/survive.i"
	@echo "... src/survive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

